<a href="https://colab.research.google.com/github/TegarFerdianW/DecisionTree/blob/main/DecisionTree_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A11.2015.09160 Tegar Ferdian Widyatmoko

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
import matplotlib.pyplot as plt

In [3]:
iris = datasets.load_iris()
features = iris['data']
target =iris['target']

In [4]:
print(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
len(features)

150

In [14]:
decisiontree = DecisionTreeClassifier(random_state=0, max_depth=None,
                                      min_samples_split=2, min_samples_leaf=1,
                                      min_weight_fraction_leaf=0,
                                      max_leaf_nodes=None,
                                      min_impurity_decrease=0)

In [16]:
model = decisiontree.fit(features, target)

In [17]:
observation =[[5,4,3,2]]
model.predict(observation)
model.predict_proba(observation)

array([[0., 1., 0.]])

In [21]:
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(decisiontree, out_file=None, feature_names=iris['feature_names'],
                                class_names=iris['target_names'])
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png('iris.png')

True

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
irisDataset = pd.read_csv('Dataset Iris.csv', delimiter=';', header=0)

In [27]:
irisDataset.head()

Id  SepalLengthCm  ...  PetalWidthCm          Species
0   1           7.00  ...          1.04  Iris-versicolor
1   2           6.04  ...          1.05  Iris-versicolor
2   3           6.09  ...          1.05  Iris-versicolor
3   4           5.05  ...          1.03  Iris-versicolor
4   5           6.05  ...          1.05  Iris-versicolor

[5 rows x 6 columns]

In [31]:
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

In [32]:
irisDataset.head

<bound method NDFrame.head of      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1           7.00          3.02           4.07          1.04        0
1     2           6.04          3.02           4.05          1.05        0
2     3           6.09          3.01           4.09          1.05        0
3     4           5.05          2.03           4.00          1.03        0
4     5           6.05          2.08           4.06          1.05        0
..  ...            ...           ...            ...           ...      ...
95   96           6.07          3.00           5.02          2.03        1
96   97           6.03          2.05           5.00          1.09        1
97   98           6.05          3.00           5.02          2.00        1
98   99           6.02          3.04           5.04          2.03        1
99  100           5.09          3.00           5.01          1.08        1

[100 rows x 6 columns]>

In [33]:
print(irisDataset)

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1           7.00          3.02           4.07          1.04        0
1     2           6.04          3.02           4.05          1.05        0
2     3           6.09          3.01           4.09          1.05        0
3     4           5.05          2.03           4.00          1.03        0
4     5           6.05          2.08           4.06          1.05        0
..  ...            ...           ...            ...           ...      ...
95   96           6.07          3.00           5.02          2.03        1
96   97           6.03          2.05           5.00          1.09        1
97   98           6.05          3.00           5.02          2.00        1
98   99           6.02          3.04           5.04          2.03        1
99  100           5.09          3.00           5.01          1.08        1

[100 rows x 6 columns]


In [34]:
irisDataset = irisDataset.drop(labels="Id", axis=1)

In [35]:
print(irisDataset)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            7.00          3.02           4.07          1.04        0
1            6.04          3.02           4.05          1.05        0
2            6.09          3.01           4.09          1.05        0
3            5.05          2.03           4.00          1.03        0
4            6.05          2.08           4.06          1.05        0
..            ...           ...            ...           ...      ...
95           6.07          3.00           5.02          2.03        1
96           6.03          2.05           5.00          1.09        1
97           6.05          3.00           5.02          2.00        1
98           6.02          3.04           5.04          2.03        1
99           5.09          3.00           5.01          1.08        1

[100 rows x 5 columns]


In [36]:
irisDataset = irisDataset.to_numpy()

In [37]:
print(irisDataset)

[[7.   3.02 4.07 1.04 0.  ]
 [6.04 3.02 4.05 1.05 0.  ]
 [6.09 3.01 4.09 1.05 0.  ]
 [5.05 2.03 4.   1.03 0.  ]
 [6.05 2.08 4.06 1.05 0.  ]
 [5.07 2.08 4.05 1.03 0.  ]
 [6.03 3.03 4.07 1.06 0.  ]
 [4.09 2.04 3.03 1.   0.  ]
 [6.06 2.09 4.06 1.03 0.  ]
 [5.02 2.07 3.09 1.04 0.  ]
 [5.   2.   3.05 1.   0.  ]
 [5.09 3.   4.02 1.05 0.  ]
 [6.   2.02 4.   1.   0.  ]
 [6.01 2.09 4.07 1.04 0.  ]
 [5.06 2.09 3.06 1.03 0.  ]
 [6.07 3.01 4.04 1.04 0.  ]
 [5.06 3.   4.05 1.05 0.  ]
 [5.08 2.07 4.01 1.   0.  ]
 [6.02 2.02 4.05 1.05 0.  ]
 [5.06 2.05 3.09 1.01 0.  ]
 [5.09 3.02 4.08 1.08 0.  ]
 [6.01 2.08 4.   1.03 0.  ]
 [6.03 2.05 4.09 1.05 0.  ]
 [6.01 2.08 4.07 1.02 0.  ]
 [6.04 2.09 4.03 1.03 0.  ]
 [6.06 3.   4.04 1.04 0.  ]
 [6.08 2.08 4.08 1.04 0.  ]
 [6.07 3.   5.   1.07 0.  ]
 [6.   2.09 4.05 1.05 0.  ]
 [5.07 2.06 3.05 1.   0.  ]
 [5.05 2.04 3.08 1.01 0.  ]
 [5.05 2.04 3.07 1.   0.  ]
 [5.08 2.07 3.09 1.02 0.  ]
 [6.   2.07 5.01 1.06 0.  ]
 [5.04 3.   4.05 1.05 0.  ]
 [6.   3.04 4.05 1.0

In [39]:
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), axis=0)
dataTesting =np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), axis=0)

In [40]:
print(dataTraining)
len(dataTraining)

[[7.   3.02 4.07 1.04 0.  ]
 [6.04 3.02 4.05 1.05 0.  ]
 [6.09 3.01 4.09 1.05 0.  ]
 [5.05 2.03 4.   1.03 0.  ]
 [6.05 2.08 4.06 1.05 0.  ]
 [5.07 2.08 4.05 1.03 0.  ]
 [6.03 3.03 4.07 1.06 0.  ]
 [4.09 2.04 3.03 1.   0.  ]
 [6.06 2.09 4.06 1.03 0.  ]
 [5.02 2.07 3.09 1.04 0.  ]
 [5.   2.   3.05 1.   0.  ]
 [5.09 3.   4.02 1.05 0.  ]
 [6.   2.02 4.   1.   0.  ]
 [6.01 2.09 4.07 1.04 0.  ]
 [5.06 2.09 3.06 1.03 0.  ]
 [6.07 3.01 4.04 1.04 0.  ]
 [5.06 3.   4.05 1.05 0.  ]
 [5.08 2.07 4.01 1.   0.  ]
 [6.02 2.02 4.05 1.05 0.  ]
 [5.06 2.05 3.09 1.01 0.  ]
 [5.09 3.02 4.08 1.08 0.  ]
 [6.01 2.08 4.   1.03 0.  ]
 [6.03 2.05 4.09 1.05 0.  ]
 [6.01 2.08 4.07 1.02 0.  ]
 [6.04 2.09 4.03 1.03 0.  ]
 [6.06 3.   4.04 1.04 0.  ]
 [6.08 2.08 4.08 1.04 0.  ]
 [6.07 3.   5.   1.07 0.  ]
 [6.   2.09 4.05 1.05 0.  ]
 [5.07 2.06 3.05 1.   0.  ]
 [5.05 2.04 3.08 1.01 0.  ]
 [5.05 2.04 3.07 1.   0.  ]
 [5.08 2.07 3.09 1.02 0.  ]
 [6.   2.07 5.01 1.06 0.  ]
 [5.04 3.   4.05 1.05 0.  ]
 [6.   3.04 4.05 1.0

80

In [41]:
print(dataTesting)
len(dataTesting)

[[5.05 2.06 4.04 1.02 0.  ]
 [6.01 3.   4.06 1.04 0.  ]
 [5.08 2.06 4.   1.02 0.  ]
 [5.   2.03 3.03 1.   0.  ]
 [5.06 2.07 4.02 1.03 0.  ]
 [5.07 3.   4.02 1.02 0.  ]
 [5.07 2.09 4.02 1.03 0.  ]
 [6.02 2.09 4.03 1.03 0.  ]
 [5.01 2.05 3.   1.01 0.  ]
 [5.07 2.08 4.01 1.03 0.  ]
 [6.07 3.01 5.06 2.04 1.  ]
 [6.09 3.01 5.01 2.03 1.  ]
 [5.08 2.07 5.01 1.09 1.  ]
 [6.08 3.02 5.09 2.03 1.  ]
 [6.07 3.03 5.07 2.05 1.  ]
 [6.07 3.   5.02 2.03 1.  ]
 [6.03 2.05 5.   1.09 1.  ]
 [6.05 3.   5.02 2.   1.  ]
 [6.02 3.04 5.04 2.03 1.  ]
 [5.09 3.   5.01 1.08 1.  ]]


20

In [52]:
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]


80

In [53]:
model = tree.DecisionTreeClassifier()

In [54]:
model = model.fit(inputTraining, labelTraining)

In [55]:
hasilPrediksi = model.predict(inputTesting)
print("Label sebenarnya : ", labelTesting)
print("Hasil Prediksi: ", hasilPrediksi)

Label sebenarnya :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Hasil Prediksi:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [56]:
prediksiBenar =(hasilPrediksi == labelTesting).sum()
prediksiSalah =(hasilPrediksi != labelTesting).sum()
print("prediksi benar : ", prediksiBenar, "data")
print("prediksi salah : ", prediksiSalah, "data")

prediksi benar :  20 data
prediksi salah :  0 data


In [57]:
print("akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

akurasi :  100.0 %
